/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.donacionesprueba.vistas;

import com.mycompany.donacionesprueba.clases.Contenido;
import com.mycompany.donacionesprueba.clases.Usuario;
import com.mycompany.donacionesprueba.dao.Dao;
import com.mycompany.donacionesprueba.vistas.influencer.PanelContenido;
import java.util.List;
import javax.swing.BoxLayout;

/**
 *
 * @author carlo
 */
public class HomeForm extends javax.swing.JFrame {

    private Usuario usuario;
    /**
     * Creates new form HomeView
     */
    public HomeForm() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    public HomeForm(Usuario usuario) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.usuario = usuario;
        
        // Seteamos el nombre del usuario en el btnProfile
        this.btnProfile.setText(this.usuario.getNombre());
        // Seteamos un box layout para el panel de posts
        this.containerPostsScroll.setLayout(new BoxLayout(containerPostsScroll, BoxLayout.Y_AXIS));
        
        initData();
    }
    
    public void initData(){
        
        this.containerPostsScroll.removeAll();

        // Cargar publicaciones del influencer
        List<Contenido> contenidos = Dao.obtenerContenidos();

        // Vamos agregando PanelContenido a containerPosts
        for (Contenido contenido : contenidos) {
            PanelContenido panelContenido = new PanelContenido(contenido, usuario);
            // Seteamos el size del panel para que se ajuste al tamaño del container
            panelContenido.setMaximumSize(panelContenido.getPreferredSize());
            panelContenido.setPreferredSize(panelContenido.getPreferredSize());
            this.containerPostsScroll.add(panelContenido);
        }

        this.containerPostsScroll.revalidate();
        this.containerPostsScroll.repaint();

    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupMenuProfile = new javax.swing.JPopupMenu();
        itemCerrarSesion = new javax.swing.JMenuItem();
        containerView = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btnProfile = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnPosts = new javax.swing.JButton();
        tabbedPane = new javax.swing.JTabbedPane();
        panelPosts = new javax.swing.JPanel();
        containerHeader = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane7 = new javax.swing.JScrollPane();
        containerPostsScroll = new javax.swing.JPanel();

        itemCerrarSesion.setText("Cerrar sesion");
        itemCerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                itemCerrarSesionMouseClicked(evt);
            }
        });
        itemCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCerrarSesionActionPerformed(evt);
            }
        });
        popupMenuProfile.add(itemCerrarSesion);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        containerView.setBackground(new java.awt.Color(255, 255, 255));
        containerView.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 134, 94));

        btnProfile.setBackground(new java.awt.Color(255, 134, 94));
        btnProfile.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnProfile.setForeground(new java.awt.Color(255, 255, 255));
        btnProfile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/donacionesprueba/vistas/assets/icon-usuario.png"))); // NOI18N
        btnProfile.setText("Nombre usuario");
        btnProfile.setBorder(null);
        btnProfile.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProfileActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Gotham Medium", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Instafluencers");

        btnPosts.setBackground(new java.awt.Color(255, 134, 94));
        btnPosts.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnPosts.setForeground(new java.awt.Color(255, 255, 255));
        btnPosts.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/donacionesprueba/vistas/assets/icon-publicaciones.png"))); // NOI18N
        btnPosts.setText("Publicaciones");
        btnPosts.setBorder(null);
        btnPosts.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnProfile, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(btnPosts, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 487, Short.MAX_VALUE)
                .addComponent(btnProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(110, 110, 110)
                    .addComponent(btnPosts, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(459, Short.MAX_VALUE)))
        );

        containerView.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 630));

        tabbedPane.setBackground(new java.awt.Color(255, 255, 255));

        panelPosts.setBackground(new java.awt.Color(255, 255, 255));
        panelPosts.setForeground(new java.awt.Color(153, 153, 153));
        panelPosts.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        containerHeader.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Gotham Medium", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 134, 94));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Publicaciones");

        javax.swing.GroupLayout containerHeaderLayout = new javax.swing.GroupLayout(containerHeader);
        containerHeader.setLayout(containerHeaderLayout);
        containerHeaderLayout.setHorizontalGroup(
            containerHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerHeaderLayout.createSequentialGroup()
                .addGap(274, 274, 274)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                .addGap(278, 278, 278))
        );
        containerHeaderLayout.setVerticalGroup(
            containerHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerHeaderLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        panelPosts.add(containerHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 6, -1, -1));

        jPanel2.setBackground(new java.awt.Color(242, 242, 242));

        jSeparator1.setBackground(new java.awt.Color(204, 204, 204));
        jSeparator1.setForeground(new java.awt.Color(153, 153, 153));

        jScrollPane7.setBorder(null);

        containerPostsScroll.setBackground(new java.awt.Color(242, 242, 242));

        javax.swing.GroupLayout containerPostsScrollLayout = new javax.swing.GroupLayout(containerPostsScroll);
        containerPostsScroll.setLayout(containerPostsScrollLayout);
        containerPostsScrollLayout.setHorizontalGroup(
            containerPostsScrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 746, Short.MAX_VALUE)
        );
        containerPostsScrollLayout.setVerticalGroup(
            containerPostsScrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 505, Short.MAX_VALUE)
        );

        jScrollPane7.setViewportView(containerPostsScroll);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 786, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(26, 26, 26)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 734, Short.MAX_VALUE)
                    .addGap(26, 26, 26)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 530, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(23, 23, 23)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 493, Short.MAX_VALUE)
                    .addGap(24, 24, 24)))
        );

        panelPosts.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 95, 780, 540));

        tabbedPane.addTab("Posts", panelPosts);

        containerView.add(tabbedPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, -40, 780, 670));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(containerView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(containerView, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProfileActionPerformed
        // TODO add your handling code here:
        //Abrimos el popup menu de lado derecho arriba
        this.popupMenuProfile.show(btnProfile, this.btnProfile.getWidth(), 0);
    }//GEN-LAST:event_btnProfileActionPerformed

    private void itemCerrarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemCerrarSesionMouseClicked
        // TODO add your handling code here:

        // Abrimos
        new Login().setVisible(true);

        this.dispose();
    }//GEN-LAST:event_itemCerrarSesionMouseClicked

    private void itemCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCerrarSesionActionPerformed
        // TODO add your handling code here:

        // Abrimos
        new Login().setVisible(true);

        this.dispose();
    }//GEN-LAST:event_itemCerrarSesionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPosts;
    private javax.swing.JButton btnProfile;
    private javax.swing.JPanel containerHeader;
    private javax.swing.JPanel containerPosts;
    private javax.swing.JPanel containerPosts1;
    private javax.swing.JPanel containerPosts2;
    private javax.swing.JPanel containerPosts3;
    private javax.swing.JPanel containerPosts4;
    private javax.swing.JPanel containerPosts5;
    private javax.swing.JPanel containerPostsScroll;
    private javax.swing.JPanel containerView;
    private javax.swing.JMenuItem itemCerrarSesion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel panelPosts;
    private javax.swing.JPopupMenu popupMenuProfile;
    private javax.swing.JTabbedPane tabbedPane;
    // End of variables declaration//GEN-END:variables
}
